_wandb:
    value:
        cli_version: 0.26.1
        e:
            hug4uitb4jthn8tan0dbhq3pgxhnu4ys:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "997182140416"
                        used: "937395589120"
                email: diegomarceloa@gmail.com
                executable: C:\Program Files\Python313\python.exe
                git:
                    commit: 0e64c379f3e12da9caf12646a9ef0e66106a614a
                    remote: https://github.com/diegomarceloa80/Dashboard_Ventas-main.git
                host: Diego-IT
                memory:
                    total: "16543780864"
                os: Windows-11-10.0.26200-SP0
                program: C:\Produccion\Dashboard_Ventas-main\train.py
                python: CPython 3.13.7
                root: C:\Produccion\Dashboard_Ventas-main
                startedAt: "2026-04-25T03:14:11.324885Z"
                writerId: hug4uitb4jthn8tan0dbhq3pgxhnu4ys
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
            "4": 3.13.7
            "5": 0.26.1
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
